"use client";
import {useEffect,useState} from "react";
import {ArrowUpRight,CalendarDays,MapPin,Play,RefreshCw,Radio,Navigation} from "lucide-react";
import type {CityEvent} from "../lib/event-listings";
import type {City} from "../lib/cities";

export function TrafficMap({city,refreshToken=0}:{city:City;refreshToken?:number}){
 const [revision,setRevision]=useState(0),[zoom,setZoom]=useState(12);
 useEffect(()=>{setZoom(12);setRevision(0)},[city.id]);
 const waze="https://embed.waze.com/iframe?"+new URLSearchParams({lat:String(city.latitude),lon:String(city.longitude),zoom:String(zoom),pin:"1"});
 const google="https://www.google.com/maps/@?"+new URLSearchParams({api:"1",map_action:"map",center:city.latitude+","+city.longitude,zoom:String(zoom),layer:"traffic"});
 return <section className="traffic-section"><div className="panel-intro"><span className="eyebrow">REAL-TIME MAP • WAZE</span><h2>Before you head out.</h2><p>Explore current traffic and community-reported incidents around {city.name}.</p></div><div className="map-toolbar"><a className="text-button" href={google} target="_blank" rel="noreferrer">Check Google traffic<ArrowUpRight size={15}/></a><span><MapPin size={16}/>{city.name}, {city.admin1}</span><label>Map view<select value={zoom} onChange={e=>setZoom(Number(e.target.value))}><option value={12}>City</option><option value={14}>Neighbourhood</option><option value={10}>Wider area</option></select></label><button aria-label="Reload traffic map" onClick={()=>setRevision(x=>x+1)}><RefreshCw size={16}/></button></div><iframe className="traffic-map" key={city.id+"-"+revision+"-"+zoom+"-"+refreshToken} src={waze} title={"Waze real-time traffic map for "+city.name} allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><p className="provider-note">Waze supplies this map; traffic overlays may be unavailable or incomplete. Check Google traffic using the link above. No visible incidents does not mean roads are clear.</p><div className="map-alternative"><div><strong>Prefer Google Maps?</strong><p>Check Google’s traffic layer for this same location.</p></div><a className="outline-button" href={google} target="_blank" rel="noreferrer">Google Maps<ArrowUpRight size={16}/></a></div><div className="subsection-title"><Navigation size={17}/><h3>Reported traffic advisories</h3><span>Recent reporting</span></div></section>
}

export function UpcomingEvents({city,refreshToken=0}:{city:City;refreshToken?:number}){
 const [retry,setRetry]=useState(0),[radius,setRadius]=useState(20),[items,setItems]=useState<CityEvent[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[updated,setUpdated]=useState("");
 const url="https://allevents.in/plugin/city-events-plugin-new.php?"+new URLSearchParams({city:city.name,state:city.admin1,latitude:String(city.latitude),longitude:String(city.longitude),radius:String(radius),popular:"0",keywords:"All",count:"12",heading:"0"});
 useEffect(()=>{
  const c=new AbortController();setItems([]);setLoading(true);setError("");setUpdated("");
  fetch("/api/events?"+new URLSearchParams({city:city.name,state:city.admin1,lat:String(city.latitude),lon:String(city.longitude),radius:String(radius)}),{signal:c.signal})
   .then(r=>{if(!r.ok)throw Error("Upcoming events are unavailable right now.");return r.json() as Promise<{items:CityEvent[];updated:string}>})
   .then(d=>{setItems(d.items);setUpdated(d.updated)}).catch(e=>{if(!c.signal.aborted)setError(e.message)}).finally(()=>{if(!c.signal.aborted)setLoading(false)});
  return()=>c.abort();
 },[city,radius,retry,refreshToken]);
 const dateLabel=(s:string)=>new Date(s).toLocaleString("en-IN",{day:"numeric",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Kolkata"});
 return <section className="events-section"><div className="panel-intro"><span className="eyebrow">UPCOMING • VIA ALLEVENTS</span><h2>Plans worth stepping out for.</h2><p>Discover events around {city.name}, with dates, venues and links to ticket options.</p></div><div className="event-source-bar"><CalendarDays size={20}/><div><strong>{city.name} event listings</strong><small>Upcoming dates • Indian Standard Time</small></div><label className="event-radius">Within<select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value={10}>10 km</option><option value={20}>20 km</option><option value={50}>50 km</option></select></label><button className="text-button" onClick={()=>setRetry(x=>x+1)} aria-label="Reload upcoming events"><RefreshCw size={15}/></button></div>
 <div aria-live="polite">{loading?<div className="empty"><RefreshCw className="spin" size={24}/><h3>Finding upcoming events…</h3></div>:error?<div className="empty" role="alert"><h3>{error}</h3><p>Try again or open the provider below.</p><button className="outline-button" onClick={()=>setRetry(x=>x+1)}>Try again</button></div>:!items.length?<div className="empty"><h3>No upcoming listings found here</h3><p>Try a wider radius or a nearby city. We only show listings with a future date.</p></div>:<div className="event-cards">{items.map(item=><article className="event-card" key={item.id}>{item.image&&<img src={item.image} alt="" loading="lazy" onError={e=>{e.currentTarget.style.display="none"}}/>}<div className="event-card-body"><time dateTime={item.start}>{dateLabel(item.start)} IST</time><h3><a href={item.url} target="_blank" rel="noreferrer">{item.title}</a></h3><p><MapPin size={15}/>{item.venue}</p><div className="event-card-bottom"><span>{item.price||"Price on booking page"}</span><a href={item.url} target="_blank" rel="noreferrer">Details & tickets<ArrowUpRight size={15}/></a></div></div></article>)}</div>}</div>
 {updated&&<p className="provider-note">Checked {dateLabel(updated)} IST · Listings via <a href="https://allevents.in/" target="_blank" rel="noreferrer">AllEvents</a></p>}<div className="map-alternative"><div><strong>More ways to find your next plan</strong><p>Confirm dates, venue and final ticket prices with the organiser.</p></div><a className="outline-button" target="_blank" rel="noreferrer" href={url}>AllEvents listings<ArrowUpRight size={16}/></a><a className="outline-button" target="_blank" rel="noreferrer" href="https://in.bookmyshow.com/explore/home">BookMyShow<ArrowUpRight size={16}/></a></div><p className="provider-note">Organiser-submitted listings may include nearby places. Availability is not guaranteed. BookMyShow opens separately; select your city there.</p></section>
}

